# Generated by Django 6.0.6 on 2026-06-05 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='user',
        ),
    ]
